using System;
using System.ComponentModel;

namespace Touba.WebApis.Api.Helpers
{
    public enum CachedItemsKeys
    {
        [Description("regions:")]
        Regions,
        [Description("countries:")]
        Countries,
        [Description("continents:")]
        Continents,
        [Description("currencies:")]
        Currencies,
        [Description("states:")]
        States,
        [Description("cities:")]
        Cities,
        [Description("salutations:")]
        Salutations,
        [Description("designations:")]
        Designations,
        [Description("maritalStates:")]
        MaritalStates,
        [Description("nationalities:")]
        Nationalities,
        [Description("qualifications:")]
        Qualifications,
        [Description("departments:")]
        Departments,
        [Description("organizations:")]
        Organizations,
        [Description("businessTypes:")]
        BusinessTypes,
        [Description("jewelryTypes:")]
        JewelryTypes,
        [Description("branches:")]
        Branches,
        [Description("activities:")]
        Activities,
        [Description("bankBranchs:")]
        BankBranches,
        [Description("bankAccountDetails:")]
        BankAccountDetails,
        [Description("donationPercentageDistributions:")]
        DonationPercentageDistributions,
        [Description("donationTypeAccountDetails:")]
        DonationTypeAccountDetails,
        [Description("donationTypeCategories:")]
        DonationTypeCategories,
        [Description("donationTypes:")]
        DonationTypes,
        [Description("paymentOrderStatuses:")]
        PaymentOrderStatuses,
        [Description("paymentOrderTypes:")]
        PaymentOrderTypes,
        [Description("religions:")]
        Religions,
        [Description("sponsorshipCancellationReasons:")]
        SponsorshipCancellationReasons,
        [Description("charityProjects:")]
        CharityProjects,
        [Description("boxShapes:")]
        BoxShapes,
        [Description("hospitals:")]
        Hospitals,
        [Description("pharmacies:")]
        Pharmacies,
        [Description("schools:")]
        Schools,
        [Description("universities:")]
        Universities,
        [Description("monthlyExpenses:")]
        MonthlyExpenses,
        [Description("monthlyIncomes:")]
        MonthlyIncomes,
        [Description("expertises:")]
        Expertises
    }
}
